### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by badboy** [clog-tool/clog-lib#14]
Hey,

we're depending on clog for parsing commits to determine a version bump. We'd like to release our library on crates, but for that we would need to depend on the crates.io-release version of clog as well.

Could you push out a new release, so we can switch over to that?

Thanks and thanks for this library!

**Comment by kbknapp** [comment]
Apologies for the time! v0.9.1 is on crates.io now

**Comment by badboy** [comment]
:+1:
